//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EndToEnd
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Trainee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Trainee()
        {
            this.Enrollments = new HashSet<Enrollment>();
        }
    
        public int TraineeID { get; set; }
        [Display(Name = "Trainee Name")]
        [StringLength(20, ErrorMessage = "The name must be under 20 characters.")]
        public string TraineeName { get; set; }
        [Display(Name = "Date of Birth")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public System.DateTime TraineeDOB { get; set; }
        [Display(Name = "Age")]
        public int TraineeAge { get; set; }
        [Display(Name = "Education")]
        [StringLength(20, ErrorMessage = "The education must be under 20 characters.")]
        public string TraineeEducation { get; set; }
        [Display(Name = "TOEIC Score")]
        [StringLength(3, ErrorMessage = "The score must be under 1000.")]
        public int TraineeTOEIC { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Enrollment> Enrollments { get; set; }
    }
}
